// flow-typed signature: 900bde53383d8681137d5ccd7ad7705a
// flow-typed version: <<STUB>>/@cityofzion/neon-js_v^2.1.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cityofzion/neon-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cityofzion/neon-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cityofzion/neon-js/lib/browser' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/lib/index' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/api/coinmarketcap' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/api/core' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/api/index' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/api/neonDB' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/api/neoscan' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/api/nep5' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/consts' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/index' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/rpc/client' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/rpc/index' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/rpc/parse' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/rpc/query' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/sc/ContractParam' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/sc/index' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/sc/opCode' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/sc/ScriptBuilder' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/transactions/components' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/transactions/core' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/transactions/exclusive' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/transactions/index' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/transactions/transaction' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/transactions/txAttrUsage' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/utils' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/wallet/Account' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/wallet/Balance' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/wallet/core' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/wallet/index' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/wallet/nep2' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/wallet/verify' {
  declare module.exports: any;
}

declare module '@cityofzion/neon-js/src/wallet/Wallet' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cityofzion/neon-js/lib/browser.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/lib/browser'>;
}
declare module '@cityofzion/neon-js/lib/index.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/lib/index'>;
}
declare module '@cityofzion/neon-js/src/api/coinmarketcap.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/api/coinmarketcap'>;
}
declare module '@cityofzion/neon-js/src/api/core.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/api/core'>;
}
declare module '@cityofzion/neon-js/src/api/index.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/api/index'>;
}
declare module '@cityofzion/neon-js/src/api/neonDB.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/api/neonDB'>;
}
declare module '@cityofzion/neon-js/src/api/neoscan.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/api/neoscan'>;
}
declare module '@cityofzion/neon-js/src/api/nep5.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/api/nep5'>;
}
declare module '@cityofzion/neon-js/src/consts.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/consts'>;
}
declare module '@cityofzion/neon-js/src/index.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/index'>;
}
declare module '@cityofzion/neon-js/src/rpc/client.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/rpc/client'>;
}
declare module '@cityofzion/neon-js/src/rpc/index.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/rpc/index'>;
}
declare module '@cityofzion/neon-js/src/rpc/parse.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/rpc/parse'>;
}
declare module '@cityofzion/neon-js/src/rpc/query.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/rpc/query'>;
}
declare module '@cityofzion/neon-js/src/sc/ContractParam.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/sc/ContractParam'>;
}
declare module '@cityofzion/neon-js/src/sc/index.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/sc/index'>;
}
declare module '@cityofzion/neon-js/src/sc/opCode.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/sc/opCode'>;
}
declare module '@cityofzion/neon-js/src/sc/ScriptBuilder.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/sc/ScriptBuilder'>;
}
declare module '@cityofzion/neon-js/src/transactions/components.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/transactions/components'>;
}
declare module '@cityofzion/neon-js/src/transactions/core.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/transactions/core'>;
}
declare module '@cityofzion/neon-js/src/transactions/exclusive.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/transactions/exclusive'>;
}
declare module '@cityofzion/neon-js/src/transactions/index.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/transactions/index'>;
}
declare module '@cityofzion/neon-js/src/transactions/transaction.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/transactions/transaction'>;
}
declare module '@cityofzion/neon-js/src/transactions/txAttrUsage.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/transactions/txAttrUsage'>;
}
declare module '@cityofzion/neon-js/src/utils.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/utils'>;
}
declare module '@cityofzion/neon-js/src/wallet/Account.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/wallet/Account'>;
}
declare module '@cityofzion/neon-js/src/wallet/Balance.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/wallet/Balance'>;
}
declare module '@cityofzion/neon-js/src/wallet/core.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/wallet/core'>;
}
declare module '@cityofzion/neon-js/src/wallet/index.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/wallet/index'>;
}
declare module '@cityofzion/neon-js/src/wallet/nep2.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/wallet/nep2'>;
}
declare module '@cityofzion/neon-js/src/wallet/verify.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/wallet/verify'>;
}
declare module '@cityofzion/neon-js/src/wallet/Wallet.js' {
  declare module.exports: $Exports<'@cityofzion/neon-js/src/wallet/Wallet'>;
}
